### ISSUE TITLE
High resolution lottie animations don't render correctly

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Lottie-Windows#471]
The Lottie Viewer has issues rendering at high resolutions.
We've supplied a sample file, but we've seen this in more than one exported Lottie animation at this resolution.

[Download sample file](https://gist.githubusercontent.com/Arlodotexe/a7fa0534a4fa342eae5cf0f6df7e6bcb/raw/69b4b32164c4f5eecec0f52d9f047b29715b6304/Microsoft%2520Lottie%2520(3840x2160).json) 3840x2160

### Lottie windows via Lottie Viewer App
![image](https://user-images.githubusercontent.com/9384894/133484738-a63ed6a3-3df8-4ba4-a028-51d09730989a.png)

### Web viewer via lottiefiles.com
![image](https://user-images.githubusercontent.com/9384894/133485198-1c9d7f9c-0e85-4d60-ba43-61163d9dd025.png)

**Comment by aborziak-ms** [comment]
> The Lottie Viewer has issues rendering at high resolutions.
> We've supplied a sample file, but we've seen this in more than one exported Lottie animation at this resolution.

 @Arlodotexe thanks for reporting this bug! I just checked your file, you can notice that it shows some issues when you open it in LottieViewer. The important one is **"LP0015. Expressions.".** As I see, you are using expressions to change scale of the objects. Unfortunately we have a limited support for expressions for now. To fix this you can try to use constant scale, or key frame animation for the scale instead of expression.

We will work on adding support for expressions in future, but right now we can't resolve this issue for this particular file.

![image](https://user-images.githubusercontent.com/83784664/133505993-0a079b34-295f-4614-9dab-afcff77b7e4c.png)

P.S.  If you see any warnings in LottieViewer it means that we can't guarantee correct rendering for now.
